GRANT ALL ON DISER TO SA;


insert into DISER.MARKET_SERVICE(ID, NAME, DESCRIPTION) values(1, '1', '1');
commit;

DROP SCHEMA DISER cascade;


create schema DISER AUTHORIZATION SA

  CREATE TABLE TELECOM_SERVICE(ID INTEGER  PRIMARY KEY NOT NULL, NAME VARCHAR(4000), DESCRIPTION VARCHAR(4000))
  CREATE TABLE MARKET_SERVICE(ID INTEGER  PRIMARY KEY NOT NULL, NAME VARCHAR(4000), DESCRIPTION VARCHAR(4000))
  CREATE TABLE MOBILE_OPERATOR(ID INTEGER  PRIMARY KEY NOT NULL, NAME VARCHAR(4000), DESCRIPTION VARCHAR(4000));


CREATE TABLE DISER.MOPER_TSERV(MOPER_ID INTEGER,
  TSERV_ID INTEGER,
  FOREIGN KEY ( MOPER_ID ) REFERENCES MOBILE_OPERATOR ( ID ),
  FOREIGN KEY ( TSERV_ID ) REFERENCES TELECOM_SERVICE ( ID ));

CREATE TABLE DISER.TSERV_MSERV(TSERV_ID INTEGER,
  MSERV_ID INTEGER,
  FOREIGN KEY ( MSERV_ID ) REFERENCES MARKET_SERVICE ( ID ),
  FOREIGN KEY ( TSERV_ID ) REFERENCES TELECOM_SERVICE ( ID ));