CREATE TABLE TELECOM_SERVICE(ID NUMBER PRIMARY KEY NOT NULL,
                              NAME VARCHAR2(4000),
                              DESCRIPTION VARCHAR2(4000));

CREATE TABLE MARKET_SERVICE(ID NUMBER PRIMARY KEY NOT NULL,
                              NAME VARCHAR2(4000),
                              DESCRIPTION VARCHAR2(4000));

CREATE TABLE MOBILE_OPERATOR(ID NUMBER PRIMARY KEY NOT NULL,
                              NAME VARCHAR2(4000),
                              DESCRIPTION VARCHAR2(4000));

CREATE TABLE DISER.MOPER_TSERV(MOPER_ID NUMBER,
  TSERV_ID NUMBER,
  FOREIGN KEY ( MOPER_ID ) REFERENCES MOBILE_OPERATOR ( ID ),
  FOREIGN KEY ( TSERV_ID ) REFERENCES TELECOM_SERVICE ( ID ));

CREATE TABLE DISER.TSERV_MSERV(TSERV_ID NUMBER,
  MSERV_ID NUMBER,
  FOREIGN KEY ( MSERV_ID ) REFERENCES MARKET_SERVICE ( ID ),
  FOREIGN KEY ( TSERV_ID ) REFERENCES TELECOM_SERVICE ( ID ));


